[phases.setup]
nixPkgs = ["python313", "playwright-driver"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "playwright install chromium"
]

[start]
cmd = "gunicorn website.main:app"